
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmSupport extends javax.swing.JFrame {

    /**
     * Creates new form jfrmSupport
     */
    public jfrmSupport() {
        initComponents();
        this.setSize(580,560);//tamaño
        this.setTitle("Motherboard");//título
        this.setLocationRelativeTo(null);//Localización
        this.setResizable(false);//Bloquear la dimensión
        jlblNom.setText(null);
        jlblPieza.setIcon(null);//me quita la imagen
        jlblNombre.setText("");//deja seleccionar mi elemento
        jtxtConcepto.setOpaque(false);
        jtxtFuncion.setOpaque(false);
        jlblConcepto.setText(null);
        jlblFuncion.setText(null);  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem19 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jlblPieza = new javax.swing.JLabel();
        jlblNombre = new javax.swing.JLabel();
        jlblConcepto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtConcepto = new javax.swing.JTextArea();
        jlblFuncion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtFuncion = new javax.swing.JTextArea();
        jlblNom = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        jMenuItem19.setText("jMenuItem19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 450));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jlblPieza.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jlblPieza.setForeground(new java.awt.Color(51, 51, 0));
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png"))); // NOI18N

        jlblNombre.setBackground(new java.awt.Color(51, 255, 0));
        jlblNombre.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N

        jlblConcepto.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jlblConcepto.setText("Concepto");

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jtxtConcepto.setColumns(20);
        jtxtConcepto.setLineWrap(true);
        jtxtConcepto.setRows(5);
        jtxtConcepto.setWrapStyleWord(true);
        jtxtConcepto.setEnabled(false);
        jScrollPane1.setViewportView(jtxtConcepto);

        jlblFuncion.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jlblFuncion.setText("Función Principal");

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        jtxtFuncion.setColumns(20);
        jtxtFuncion.setLineWrap(true);
        jtxtFuncion.setRows(5);
        jtxtFuncion.setWrapStyleWord(true);
        jtxtFuncion.setEnabled(false);
        jScrollPane2.setViewportView(jtxtFuncion);

        jlblNom.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jlblNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNom.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jlblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)))
                        .addComponent(jlblNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jlblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblNombre)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblConcepto)
                        .addComponent(jlblFuncion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jMenu1.setMnemonic('A');
        jMenu1.setText("Archivo");

        jMenuItem1.setMnemonic('a');
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setMnemonic('g');
        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setMnemonic('s');
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componentes de la PC");

        jMenuItem4.setText("PlacaBase");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Ram");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente De Poder");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Disco Duro(HDD)");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Unidad SSD");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Tarjeta de Video");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Tarjeta de Red");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Ventilador del Gabinete");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Tarjeta de Sonido");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Batería CMOS");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Cable SATA");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Cable de alimentación");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("BIOS/UEFI");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem20.setText("Acerca del Programa");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuItem21.setText("Créditos");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem21);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int msg=JOptionPane.showConfirmDialog(null, "Desea Salir del Software🤪");
        if (msg==0)
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Motherboard");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText("La motherboard es la tarjeta principal de la computadora"
                +"donde se conectan todos los componentes");
        jtxtFuncion.setText("Permite la comunicación entre el procesador, la memoria RAM, "
                +"el almacenamiento y los demás dispositivos.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png")));
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Procesador");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText("El procesador es el cerebro de la computadora " 
        + "y se encarga de ejecutar las instrucciones de los programas.");
        jtxtFuncion.setText(
        "Procesa la información y controla el funcionamiento "
        + "de todos los componentes del equipo.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cpu.png")));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Ram");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "La memoria RAM almacena temporalmente la información "
        + "que utilizan los programas mientras "
        + "están en ejecución.");
        jtxtFuncion.setText(
        "Permite ejecutar varios programas al mismo tiempo "
        + "de forma rápida y eficiente.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ram.png")));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Cooler");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "El cooler del procesador es un sistema "
        + "de enfriamiento que mantiene "
        + "una temperatura adecuada.");
        jtxtFuncion.setText(
        "Disipa el calor generado por el procesador "
        + "para evitar el sobrecalentamiento.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cooler.png")));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Fuente");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "La fuente de poder es el componente encargado "
        + "de suministrar energía eléctrica "
        + "a la computadora.");
        jtxtFuncion.setText(
        "Convierte la corriente eléctrica y distribuye "
        + "la energía a todos los componentes del equipo.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fuente.png")));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Ventilador Del Gabinete");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "El ventilador del gabinete ayuda "
        + "a mantener una buena circulación "
        + "de aire dentro de la computadora.");
        jtxtConcepto.setText(
        "El ventilador del gabinete ayuda "
        + "a mantener una buena circulación "
        + "de aire dentro de la computadora.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventiladordelgabinete.png")));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Disco Duro HDD");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "El disco duro es un dispositivo de almacenamiento "
        + "permanente donde se guardan el sistema operativo, "
        + "los programas y los archivos.");
        jtxtFuncion.setText(
        "Almacena información y conserva los datos "
        + "aunque la computadora esté apagada.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DiscoDuroHDD.png")));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Unidad SSD");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText("La unidad SSD es un dispositivo de almacenamiento"
        + "que utiliza memoria flash para guardar información "
        + "de forma rápida");        
        jtxtFuncion.setText(
        "Almacena datos y mejora la velocidad "
       + "de inicio del sistema y de los programas.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Unidad SSD.png")));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Tarjeta De Video");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "La tarjeta de video es el componente encargado "
        + "de procesar y mostrar las imágenes "
        + "en el monitor.");
        jtxtFuncion.setText(
        "Procesa gráficos, videos y juegos "
        + "para ofrecer una mejor calidad de imagen.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetaDeVideo.png")));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Tarjeta De Red");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "La tarjeta de red permite que la computadora "
        + "se conecte a una red local "
        + "o a Internet.");
        jtxtFuncion.setText(
        "Envía y recibe datos entre la computadora "
        + "y otras redes o dispositivos.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetadeRed.png")));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Tarjeta De sonido");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "La tarjeta de sonido es el componente "
        + "encargado de procesar el audio "
        + "de la computadora.");
        jtxtFuncion.setText(
        "Permite la reproducción y grabación de sonido "
        + "mediante bocinas y micrófonos.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tarjetadesonido.png")));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Batería CMOS");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "La batería CMOS alimenta la memoria "
        + "donde se guarda la configuración "
        + "del BIOS y la fecha y hora.");
        
        jtxtFuncion.setText(
        "Mantiene la configuración del BIOS "
        + "y el reloj del sistema cuando "
        + "la computadora está apagada.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Batería CMOS.png")));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Cable SATA");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "El cable SATA es un cable de datos "
        + "utilizado para conectar discos duros "
        + "y unidades SSD a la motherboard."); 
        jtxtFuncion.setText(
        "Transmite datos entre el dispositivo "
        + "de almacenamiento y la motherboard.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SATA.png")));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("Cable de Alimentación");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
       "El cable de alimentación proporciona "
       + "energía eléctrica desde la fuente de poder "
       + "a los diferentes componentes.");
        jtxtFuncion.setText(
       "Suministra la energía necesaria "
       + "para el funcionamiento de los dispositivos internos.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cabledepoder.png")));
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        jlblPieza.setText("");
        jlblNom.setText("BIOS/UEFI");
        jlblNom.setForeground(Color.white);
        jtxtConcepto.setText(
        "El BIOS o UEFI es un firmware "
        + "que inicia la computadora y verifica "
        + "el funcionamiento del hardware.");
        jtxtFuncion.setText(
        "Inicializa el hardware y permite "
        + "el arranque del sistema operativo.");
        jlblPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BIOS_UEFI.png")));
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        JOptionPane.showMessageDialog(this, 
        "Este programa fue echo\npara realizar la tarea\nde la guia de aprendizaje número 3", 
        "Acerca del programa",
        JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        JOptionPane.showMessageDialog(this,
        "Echo por: Daniel Zea\nCurso:Computación",
        "Créditos",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmSupport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel jlblConcepto;
    private javax.swing.JLabel jlblFuncion;
    private javax.swing.JLabel jlblNom;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblPieza;
    private javax.swing.JTextArea jtxtConcepto;
    private javax.swing.JTextArea jtxtFuncion;
    // End of variables declaration//GEN-END:variables
}
